services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    environment:
      # : -default => default value ${DB_USER: - james}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
